### PR TITLE
Fix unsafe pointer conversions caught by Go 1.14 checkptr

### LINKED ISSUE #187: panic: runtime error: unsafe pointer conversion (Go 1.14)
In Go 1.14 there is now checks of pointer conversions with the requirement that they should align to the "natural size".

It seems like they decided to make this enabled when `-race` is specified: https://github.com/golang/go/issues/34964

This leads to crashes like this:

```
    --- FAIL: TestNewBoltStore/Basic (0.00s)
panic: runtime error: unsafe pointer conversion [recovered]
	panic: runtime error: unsafe pointer conversion
goroutine 6 [running]:
testing.tRunner.func1(0xc000100360)
	/home/travis/.gimme/versions/go/src/testing/testing.go:916 +0xaeb
panic(0x6b5ee0, 0xc00000e260)
	/home/travis/.gimme/versions/go/src/runtime/panic.go:967 +0x396
github.com/etcd-io/bbolt.(*freelist).write(0xc0000fc080, 0xc0000ff000, 0xc0000ff000, 0x0)
	/home/travis/gopath/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/freelist.go:318 +0xe9
github.com/etcd-io/bbolt.(*Tx).commitFreelist(0xc00011a0e0, 0x2, 0x7f603f3d1000)
	/home/travis/gopath/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/tx.go:234 +0x204
github.com/etcd-io/bbolt.(*Tx).Commit(0xc00011a0e0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/tx.go:175 +0x7d6
github.com/etcd-io/bbolt.(*DB).Update(0xc000106000, 0xc00005abf8, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/etcd-io/bbolt@v1.3.3/db.go:701 +0x174
...
```

### PR DESCRIPTION
**Pull request by jrick**
Go 1.14 introduces a checkptr debug flag for the compiler, which is enabled by default with -race and can be enabled separately with `-gcflags=all=-d=checkptr`.  checkptr enables two checks during type conversions of unsafe.Pointer:

1. All unsafe pointer conversions to type *T2 must have proper alignment for type T2

2. All unsafe pointer conversions from *T1 to unsafe.Pointer to *T2 must not cause the new allocation to span more than two separate Go heap allocations.

bbolt was performing unsafe pointer conversions that were failing each of these checks.

This change modifies bbolt to avoid type conversions that are both caught by the new checks and were previously invalid according to the Go memory model.  Rather than subslicing arrays of "max allocations" number of elements, slices are created with the precise sizes required.  This change also removes all unaligned access even on architectures where the hardware permits it.

The performance hit, if any, for removing unaligned access appears negligible according to the project's benchmarks:

```
% go test -run none -bench 'Benchmark*'
seed: 84000
quick settings: count=5, items=1000, ksize=1024, vsize=1024
goos: darwin
goarch: amd64
pkg: go.etcd.io/bbolt
Benchmark_FreelistRelease10K-24       	    3757	    302905 ns/op
Benchmark_FreelistRelease100K-24      	     294	   4076518 ns/op
Benchmark_FreelistRelease1000K-24     	      16	  66904544 ns/op
Benchmark_FreelistRelease10000K-24    	       1	1183743396 ns/op
BenchmarkDBBatchAutomatic-24          	      63	  16815505 ns/op
BenchmarkDBBatchSingle-24             	       1	14088192506 ns/op
BenchmarkDBBatchManual10x100-24       	       8	 141973506 ns/op
PASS
ok  	go.etcd.io/bbolt	25.682s
% git checkout master                  
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
% go test -run none -bench 'Benchmark*' -args -quick.seed=84000
seed: 84000
quick settings: count=5, items=1000, ksize=1024, vsize=1024
goos: darwin
goarch: amd64
pkg: go.etcd.io/bbolt
Benchmark_FreelistRelease10K-24       	    3794	    303829 ns/op
Benchmark_FreelistRelease100K-24      	     294	   4084449 ns/op
Benchmark_FreelistRelease1000K-24     	      15	  66988066 ns/op
Benchmark_FreelistRelease10000K-24    	       1	1156598746 ns/op
BenchmarkDBBatchAutomatic-24          	      62	  17064184 ns/op
BenchmarkDBBatchSingle-24             	       1	13940793747 ns/op
BenchmarkDBBatchManual10x100-24       	       8	 141596004 ns/op
PASS
ok  	go.etcd.io/bbolt	24.129s
```

Fixes #187.

### CODE REVIEW

File: bucket.go [hunk 1]
```diff
@@ -123,8 +123,11 @@ func (b *Bucket) Bucket(name []byte) *Bucket {
 func (b *Bucket) openBucket(value []byte) *Bucket {
 	var child = newBucket(b.tx)
 
-	// Unaligned pointer access requires a copy to be made.
-	const unalignedMask = unsafe.Alignof(uintptr(0)) - 1
+	// Unaligned access requires a copy to be made.
+	const unalignedMask = unsafe.Alignof(struct {
+		bucket
+		page
+	}{}) - 1
```
Comment (jrick) [inline bucket.go]: I don't have any 32-bit hardware available (i386, armv7, etc) so if someone could test whether this still passes with `-gcflags=all=-d=checkptr` on these architectures I'd love to know.  My concern is that the allocation for the copied byte slice below will be pointer aligned (4 bytes), and not aligned for the 64-bit fields of these structs (8 bytes).

**Comment by qbit** [comment]
On Sat, 08 Feb 2020 at 00:17:10 -0800, Josh Rickmar wrote:
> jrick commented on this pull request.
> 
> 
> 
> > @@ -123,8 +123,11 @@ func (b *Bucket) Bucket(name []byte) *Bucket {
>  func (b *Bucket) openBucket(value []byte) *Bucket {
>  	var child = newBucket(b.tx)
>  
> -	// Unaligned pointer access requires a copy to be made.
> -	const unalignedMask = unsafe.Alignof(uintptr(0)) - 1
> +	// Unaligned access requires a copy to be made.
> +	const unalignedMask = unsafe.Alignof(struct {
> +		bucket
> +		page
> +	}{}) - 1
> 
> I don't have any 32-bit hardware available (i386, armv7, etc) so if someone could test whether this still passes with `-gcflags=all=-d=checkptr` on these architectures I'd love to know.  My concern is that the allocation for the copied byte slice below will be pointer aligned (4 bytes), and not aligned for the 64-bit fields of these structs (8 bytes).

Tested on OpenBSD i386:

go test -gcflags=all=-d=checkptr 
seed: 24103
quick settings: count=5, items=1000, ksize=1024, vsize=1024
00010000000000000000000000000000
unexpected fault address 0x6f010040
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6f010040 pc=0x8169ebd]

goroutine 42 [running]:
runtime.throw(0x8202ba8, 0x5)
        /home/qbit/go/src/runtime/panic.go:1112 +0x64 fp=0x4f086e44
sp=0x4f086e30 pc=0x8077674
runtime.sigpanic()
        /home/qbit/go/src/runtime/signal_unix.go:694 +0x2fe fp=0x4f086e5c
sp=0x4f086e44 pc=0x808bb0e
go.etcd.io/bbolt.(*DB).meta(0x4f07c000, 0x3)
        /home/qbit/bbolt/db.go:901 +0x1d fp=0x4f086e74 sp=0x4f086e5c
pc=0x8169ebd
go.etcd.io/bbolt.(*DB).hasSyncedFreelist(...)
        /home/qbit/bbolt/db.go:323
go.etcd.io/bbolt.(*Tx).rollback(0x4f068480)
        /home/qbit/bbolt/tx.go:280 +0x63 fp=0x4f086e90 sp=0x4f086e74
pc=0x8173343
go.etcd.io/bbolt.(*Tx).Commit(0x4f068480, 0x0, 0x0)
        /home/qbit/bbolt/tx.go:162 +0x481 fp=0x4f086f30 sp=0x4f086e90
pc=0x8172e01
go.etcd.io/bbolt.(*DB).Update(0x4f07c000, 0x4f086f84, 0x0, 0x0)
        /home/qbit/bbolt/db.go:701 +0xd1 fp=0x4f086f60 sp=0x4f086f30
pc=0x8169511
go.etcd.io/bbolt_test.TestDB_Put_VeryLarge(0x4f05c000)
        /home/qbit/bbolt/bucket_test.go:221 +0xfb fp=0x4f086fa8 sp=0x4f086f60
pc=0x818001b
testing.tRunner(0x4f05c000, 0x820fa78)
        /home/qbit/go/src/testing/testing.go:993 +0xae fp=0x4f086fe8
sp=0x4f086fa8 pc=0x812640e
runtime.goexit()
        /home/qbit/go/src/runtime/asm_386.s:1337 +0x1 fp=0x4f086fec
sp=0x4f086fe8 pc=0x80a2d51
created by testing.(*T).Run
        /home/qbit/go/src/testing/testing.go:1044 +0x2a7

goroutine 1 [chan receive]:
testing.(*T).Run(0x4f05c000, 0x82063f5, 0x14, 0x820fa78, 0x301)
        /home/qbit/go/src/testing/testing.go:1045 +0x2c6
testing.runTests.func1(0x4f05c140)
        /home/qbit/go/src/testing/testing.go:1286 +0x54
testing.tRunner(0x4f05c140, 0x4f02068c)
        /home/qbit/go/src/testing/testing.go:993 +0xae
testing.runTests(0x4f00c060, 0x83683e0, 0xab, 0xab, 0x1)
        /home/qbit/go/src/testing/testing.go:1284 +0x227
testing.(*M).Run(0x4f038100, 0x0)
        /home/qbit/go/src/testing/testing.go:1201 +0x10e
go.etcd.io/bbolt_test.TestMain(0x4f038100)
        /home/qbit/bbolt/quick_test.go:37 +0x3bc
main.main()
        _testmain.go:418 +0xfa
exit status 2
FAIL    go.etcd.io/bbolt        6.815s

> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/etcd-io/bbolt/pull/201#pullrequestreview-355536979

-- 
PGP: 0x1F81112D62A9ADCE / 3586 3350 BFEA C101 DB1A  4AF0 1F81 112D 62A9 ADCE

**Comment by jrick** [comment]
That looks like #183.

**Comment by arjunsingri** [comment]
Is there a timeline of when this will be merged?

**Comment by jeffallen** [comment]
Ping @xiang90, @gyuho @vorburger ? This is a pretty important change, not having it checked in prevents all users of boltdb from upgrading to Go 1.14. Do you need more committers on the boltdb team?

**Comment by vorburger** [comment]
Sorry I'm not currently active in this project.

**Comment by gyuho** [comment]
@jrick Can we squash commits?

**Comment by jrick** [comment]
@gyuho done.

File: go.mod [hunk 2]
```diff
@@ -1,3 +1,5 @@
 module go.etcd.io/bbolt
 
 go 1.12
```
Comment (gyuho) [inline go.mod]: Can we bump up to `1.14` as well?

Comment (jrick) [reply go.mod]: Shouldn't be necessary. The Go version in the go.mod is the minimum supported Go version, and this still works fine with Go 1.12.  Changing it is also unrelated to this fix, but you could change it in a different commit later...

**Comment by gyuho** [comment]
@jrick Thanks for the fix.

File: bolt_arm.go [hunk 3]
```diff
@@ -7,22 +7,3 @@ const maxMapSize = 0x7FFFFFFF // 2GB
...
-	// correctly.
-
-	// ARM9 and older devices require load/stores to be from/to aligned
-	// addresses. If not, the lower 2 bits are cleared and that address is
-	// read in a jumbled up order.
-
-	// See http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka15414.html
-
-	raw := [6]byte{0xfe, 0xef, 0x11, 0x22, 0x22, 0x11}
-	val := *(*uint32)(unsafe.Pointer(uintptr(unsafe.Pointer(&raw)) + 2))
```
Comment (tmm1) [inline bolt_arm.go]: Build is now failing on arm:

>bolt_arm.go:3:8: imported and not used: "unsafe"

Comment (jrick) [reply bolt_arm.go]: sorry :(  didn't try a cross compile, which would have caught that

File: freelist.go [hunk 4]
```diff
@@ -267,17 +284,21 @@ func (f *freelist) read(p *page) {
...
 	}
 
 	// Copy the list of page ids from the freelist.
 	if count == 0 {
 		f.ids = nil
 	} else {
-		ids := ((*[maxAllocSize]pgid)(unsafe.Pointer(&p.ptr)))[idx : idx+count]
+		ids := *(*[]pgid)(unsafe.Pointer(&reflect.SliceHeader{
+			Data: uintptr(unsafe.Pointer(p)) + unsafe.Sizeof(*p) + idx*unsafe.Sizeof(pgid(0)),
+			Len:  int(count),
```
Comment (AskAlexSharov) [inline freelist.go]: here must be `idx`?

Comment (jrick) [reply freelist.go]: the code this replaced had len count as well.

Comment (AskAlexSharov) [reply freelist.go]: i see code before was: [idx:idx+count]
Means len=idx and cap=idx+count ?

Comment (jrick) [reply freelist.go]: no
