### PR TITLE
Fix progress reporting in bench cmd

### LINKED ISSUE #428: bench: read: read seq: iter mismatch
To reproduce run:
> go run ./cmd/bbolt/ bench -count 100000

results in:
```
starting write benchmark.
starting read benchmark.
bench: read: read seq: iter mismatch: expected 100000, got 200000
exit status 1
```

after bisecting, it seems this was introduced with https://github.com/etcd-io/bbolt/pull/420

### PR DESCRIPTION
**Pull request by cenkalti**
Fix #428

### CODE REVIEW

File: cmd/bbolt/main.go [hunk 1]
```diff
@@ -1166,9 +1166,7 @@ func (cmd *benchCommand) runWrites(db *bolt.DB, options *BenchOptions, results *
 		cmd.startProfiling(options)
 	}
 
-	finishChan := make(chan interface{})
-	go checkProgress(results, finishChan, cmd.Stderr)
-	defer close(finishChan)
+	defer results.StartProgress(cmd.Stderr).StopProgress()
```
Comment (ahrtr) [inline cmd/bbolt/main.go:1169]: I tend to keep the previous implementation, which has better readability to me. It also looks weird to bind methods `StartProgress` and `StopProgress` with receiver `results *BenchResults`; the methods do not actually start or stop the read/write process, instead they create the monitoring goroutine.

File: cmd/bbolt/main.go [hunk 2]
```diff
@@ -1234,13 +1232,16 @@ func (cmd *benchCommand) runWritesWithSource(db *bolt.DB, options *BenchOptions,
 				if err := b.Put(key, value); err != nil {
 					return err
 				}
+
+				results.AddCompletedOps(1)
```
Comment (ahrtr) [inline cmd/bbolt/main.go:1236]: nice!

File: cmd/bbolt/main.go [hunk 3]
```diff
@@ -1234,13 +1232,16 @@ func (cmd *benchCommand) runWritesWithSource(db *bolt.DB, options *BenchOptions,
...
 			}
 
+			results.ReportProgress()
```
Comment (ahrtr) [inline cmd/bbolt/main.go:1239]: See my comment above.
```suggestion
```

File: cmd/bbolt/main.go [hunk 4]
```diff
@@ -1234,13 +1232,16 @@ func (cmd *benchCommand) runWritesWithSource(db *bolt.DB, options *BenchOptions,
...
+			fmt.Fprintf(cmd.Stderr, "Committing transaction...\n")
```
Comment (ahrtr) [inline cmd/bbolt/main.go:1240]: The committing operation is transparent to users. How about add `fmt.Fprintf(cmd.Stderr, "Starting write iteration %d\n", i)` and `fmt.Fprintf(cmd.Stderr, "Finished write iteration %d\n", i)` at the begin and end respectively?

File: cmd/bbolt/main.go [hunk 5]
```diff
@@ -1277,13 +1278,16 @@ func (cmd *benchCommand) runWritesNestedWithSource(db *bolt.DB, options *BenchOp
...
```
Comment (ahrtr) [inline cmd/bbolt/main.go:1286]: ditto

File: cmd/bbolt/main.go [hunk 6]
```diff
@@ -1394,20 +1394,43 @@ func (cmd *benchCommand) runReadsSequentialNested(db *bolt.DB, options *BenchOpt
...
+	close(r.stop)
+}
+
+// ReportProgress immediately without waiting for the next tick.
+func (r *BenchResults) ReportProgress() {
+	select {
+	case r.report <- struct{}{}:
+	default:
+	}
+}
```
Comment (ahrtr) [inline cmd/bbolt/main.go:1416]:
```suggestion
```

**Comment by ahrtr** [comment]
cc @tjungblu

File: cmd/bbolt/main.go [hunk 7]
```diff
@@ -1394,20 +1394,43 @@ func (cmd *benchCommand) runReadsSequentialNested(db *bolt.DB, options *BenchOpt
...
-			fmt.Fprintf(stderr, "Completed %d requests, %d/s \n",
-				completed, ((completed-lastCompleted)*int64(time.Second))/int64(taken),
-			)
-			lastCompleted, lastTime = completed, t
+		case <-r.report:
+			t = time.Now()
+		case t = <-time.After(time.Second):
 		}
+		completed, taken := r.CompletedOps(), t.Sub(lastTime)
+		fmt.Fprintf(w, "Completed %d requests, %d/s \n",
```
Comment (tjungblu) [inline cmd/bbolt/main.go:1430]: I don't know if you want to track this with a log file on every line individually, but for the sake of console spam, maybe add a CR?

**Review by tjungblu — COMMENTED** [review]
lgtm (non-binding) and thanks for fixing it (again)

File: cmd/bbolt/main.go (hunk 1 above)
Comment (cenkalti) [reply cmd/bbolt/main.go:1169]: It doesn't start/stop read/write "process", it starts/stops "progress". I can rename it as `StartMonitoring`/`StopMonitoring` if it's confusing.

Chaining method calls in defer is pretty common pattern actually. One example from [stdlib](https://pkg.go.dev/runtime/trace#StartRegion):
> defer trace.StartRegion(ctx, "myTracedRegion").End()

If you're still not okay with this, I can revert the whole change but only keep `sync/atomic` changes that fixes the bug.

File: cmd/bbolt/main.go (hunk 3 above)
Comment (cenkalti) [reply cmd/bbolt/main.go:1239]: This is required to trigger reporting progress before waiting for the next tick. Without this, the last operation/s number would be wrong because there would not be enough operations on the last period to fill the whole second.

File: cmd/bbolt/main.go (hunk 7 above)
Comment (cenkalti) [reply cmd/bbolt/main.go:1425]: Sorry @tjungblu . I couldn't understand your comment. The aim of this CR is to enable reporting progress on console while the benchmark is running. Can you elaborate a bit more on this?

File: cmd/bbolt/main.go (hunk 4 above)
Comment (cenkalti) [reply cmd/bbolt/main.go]: Done.

File: cmd/bbolt/main.go (hunk 6 above)
Comment (cenkalti) [reply cmd/bbolt/main.go]: If you feel like these progress related methods should not belong to `BenchResults` struct, I can move them under a new type. Please let me know.

**Comment by cenkalti** [comment]
Output after latest push on this CR:
```
% go run ./cmd/bbolt/ bench -count 5000000
starting write benchmark.
Starting write iteration 0
Completed 1466160 requests, 1465434/s
Completed 2772700 requests, 1306436/s
Completed 4053350 requests, 1280549/s
Completed 5000000 requests, 1553296/s
Finished write iteration 0
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
Completed 5000000 requests, 0/s
starting read benchmark.
Completed 42853508 requests, 42819649/s
# Write 5000000(ops)    13.873989083s   (2.774µs/op)    (360490 op/sec)
# Read  45000000(ops)   1.050179107s    (23ns/op)       (43478260 op/sec)
```

If you feel like printing progress after write iteration done (during commit phase) is unnecessary, I can make the progress reporting stop earlier.

File: cmd/bbolt/main.go (hunk 1 above)
Comment (ahrtr) [reply cmd/bbolt/main.go:1169]: > Chaining method calls in defer is pretty common pattern actually. One example from stdlib:

Thanks for the clarification. It seems like a separate enhancement. You enhanced the progress goroutine,  not only print progress info periodically, but also on demand. Can we review this in a separate PR?

> only keep sync/atomic changes that fixes the bug.

That would be a straightforward change, and should be approved & merged soon.

**Comment by cenkalti** [comment]
@ahrtr Comments addressed. Can you take another look?

**Review by ahrtr — APPROVED** [review]
LGTM

Thank you @cenkalti

File: cmd/bbolt/main.go (hunk 7 above)
Comment (tjungblu) [reply cmd/bbolt/main.go]: perfect, then why print a line for each instead of using a carriage return to have the progress report in a single line?

**Review by ptabor — APPROVED** [review]
